# Generated by Django 2.2.19 on 2021-04-05 18:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caramelo',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
