# Generated by Django 2.2.19 on 2021-04-05 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_caramelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='caramelo',
        ),
    ]
